export const LOAD_USER_DATA = "LOAD_USER_DATA";
export const LOAD_SUCCESS_DATA = "LOAD_SUCCESS_DATA";
export const LOAD_ERORR_DATA = "LOAD_SUCCESS_DATA";

export const CREATE_USER_DATA = "CREATE_USER_DATA";
export const CREATE_SUCCESS_DATA = "CREATE_SUCCESS_DATA";
export const CREATE_ERORR_DATA = "LOAD_SUCCESS_DATA";

export const DEL_USER_DATA = "DEL_USER_DATA";
export const DEL_SUCCESS_DATA = "DEL_SUCCESS_DATA";
export const DEL_ERORR_DATA = "DEL_SUCCESS_DATA";

export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const UPDATE_SUCCESS_DATA = "UPDATE_SUCCESS_DATA";
export const UPDATE_ERORR_DATA = "UPDATE_ERORR_DATA";

export const FILTER_USER_DATA = "FILTER_USER_DATA";
export const FILTER_SUCCESS_DATA = "FILTER_SUCCESS_DATA";
export const FILTER_ERORR_DATA = "FILTER_ERORR_DATA";
